### ISSUE TITLE
Seems not functional  on ubuntu

### ISSUE THREAD

**Issue by SunAnLan** [gnawice/mojo-cnn#2]
it seems missing tchar.h and wondering which version of OpenCV are you using?

**Comment by xyjdreamer** [comment]
tchar.h is only supported in windows paltform. I think.

**Comment by SunAnLan** [comment]
agree with that. But seems what wiki said means this one should be functional on ubuntu. Did I misunderstand that?

**Comment by Adliyan** [comment]
It can run under vs2010, why I am at compile time error 2001 can not resolve the external symbols class mojo :: matrix __cdecl transformm?

**Comment by gnawice** [comment]
I'll try to address in the next couple days.

**Comment by gnawice** [comment]
I removed tchar.h and everything seems to compile and run fine.

OpenCV 2.x and 3.x should work, though you may need to edit paths,makefiles and pragmas for libs

**Comment by gnawice** [comment]
I've validated non-opencv builds with GCC.
