### ISSUE TITLE
vgg16.mojo missing

### ISSUE THREAD

**Issue by bonseyes-admin** [gnawice/mojo-cnn#3]
vgg16.mojo is not in the models directory however referenced int the vgg.cpp example.

**Comment by gnawice** [comment]
The example file header explains to download the model from  https://drive.google.com/file/d/0B5Dx9ePCIXQAZU51T0MyQXpvOXc/view?usp=sharing

**Comment by bonseyes-admin** [comment]
Thanks great missed that. Do you have any models like Googlenet trained in mojo-cnn?

**Comment by gnawice** [comment]
Sorry, unfortunately not.
