### ISSUE TITLE
__pragma not declared in this scope

### ISSUE THREAD

**Issue by tarzan212** [gnawice/mojo-cnn#7]
I am executing the makefile on the test folder using mingw32-make. I get plenty of message errors stating that __pragma is not declared along with "omp", followed by multiple error that are consequences of the previous.

**Comment by gnawice** [comment]
I've added travis and appveyor CI to ensure builds are working with GCC and MSVC.  I suspect you'll need to either disable OpenMP in mojo or find out how to get openmp support in mingw32.

**Comment by gnawice** [comment]
Sorry, Only tested in GCC and MSVC.  You can likely remove the define for
using OMP and threading so that those pragmas are skipped.
