### ISSUE TITLE
Network destructor clears pointer container without freeing and while indexing the same

### ISSUE THREAD

**Issue by TechnikEmpire** [gnawice/mojo-cnn#8]
**Describe the bug**
In the network destructor, `layer_sets` is looped over with an index `i` and then each pointer in the nested container ` layer_sets[i]` is deleted. However, the first such call is immediately followed by `layer_sets.clear()` when it ought to be `layer_sets[i].clear()`, which will leak all the rest of the memory not yet manually freed.

**To Reproduce**
Use the network class.

**Expected behavior**
`layer_sets[i].clear()` should be called, not `layer_sets.clear()`.

By the way I'm porting this to C++AMP which is how I found the issue. Thanks for publishing this.

**Comment by gnawice** [comment]
Thanks
